server.port=8080

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

jwt.secret=ClassConnectSecretKeyForJWTSigningMustBeAtLeast256BitsLong12345
jwt.expiration=86400000

app.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
